
version: '2'

services:

  fundorderer.funds.com:
    container_name: fundorderer.funds.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=fundorderer
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/funds.com/orderers/fundorderer.funds.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/funds.com/orderers/fundorderer.funds.com/tls/:/var/hyperledger/orderer/tls
    - ../prod/fundorderer:/var/hyperledger/production
    ports:
      - 7050:7050

  peer0.maple.funds.com:
    container_name: peer0.maple.funds.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.maple.funds.com
      - CORE_PEER_ADDRESS=peer0.maple.funds.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.maple.funds.com:7051
      - CORE_PEER_LOCALMSPID=maple
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=admin
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/maple.funds.com/peers/peer0.maple.funds.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/maple.funds.com/peers/peer0.maple.funds.com/tls:/etc/hyperledger/fabric/tls
        - ../prod/peer0-maple:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.maple.funds.com:
    container_name: peer1.maple.funds.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.maple.funds.com
      - CORE_PEER_ADDRESS=peer1.maple.funds.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.maple.funds.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.maple.funds.com:7051
      - CORE_PEER_LOCALMSPID=maple
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/maple.funds.com/peers/peer1.maple.funds.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/maple.funds.com/peers/peer1.maple.funds.com/tls:/etc/hyperledger/fabric/tls
        - ../prod/peer1-maple:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053

  peer0.fundinc.funds.com:
    container_name: peer0.fundinc.funds.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.fundinc.funds.com
      - CORE_PEER_ADDRESS=peer0.fundinc.funds.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.fundinc.funds.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.fundinc.funds.com:7051
      - CORE_PEER_LOCALMSPID=fundinc
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/fundinc.funds.com/peers/peer0.fundinc.funds.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/fundinc.funds.com/peers/peer0.fundinc.funds.com/tls:/etc/hyperledger/fabric/tls
        - ../prod/peer0-fundinc:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.fundinc.funds.com:
    container_name: peer1.fundinc.funds.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.fundinc.funds.com
      - CORE_PEER_ADDRESS=peer1.fundinc.funds.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.fundinc.funds.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.fundinc.funds.com:7051
      - CORE_PEER_LOCALMSPID=fundinc
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/fundinc.funds.com/peers/peer1.fundinc.funds.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/fundinc.funds.com/peers/peer1.fundinc.funds.com/tls:/etc/hyperledger/fabric/tls
        - ../prod/peer1-fundinc:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053
