
version: '2'

networks:
  byfn:

services:

  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
    networks:
        - byfn

  fundorderer.funds.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: fundorderer.funds.com
    container_name: fundorderer.funds.com
    networks:
      - byfn

  peer0.maple.funds.com:
    container_name: peer0.maple.funds.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.maple.funds.com
    depends_on:
      - couchdb0
    networks:
      - byfn

  peer1.maple.funds.com:
    container_name: peer1.maple.funds.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.maple.funds.com
    networks:
      - byfn

  peer0.fundinc.funds.com:
    container_name: peer0.fundinc.funds.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.fundinc.funds.com
    networks:
      - byfn

  peer1.fundinc.funds.com:
    container_name: peer1.fundinc.funds.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.fundinc.funds.com
    networks:
      - byfn

  camaple.funds.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=camaple.funds.com
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.maple.funds.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/01270b66881819b9512916bb7dc40acc3f71300aeab7a54ff656049f743e5ae7_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/maple.funds.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: camaple.funds.com
    networks:
        - byfn
      
  cli_maple:
    container_name: cli_maple
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli_maple
      - CORE_PEER_ADDRESS=peer0.maple.funds.com:7051
      - CORE_PEER_LOCALMSPID=maple
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/maple.funds.com/peers/peer0.maple.funds.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/maple.funds.com/peers/peer0.maple.funds.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/maple.funds.com/peers/peer0.maple.funds.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/maple.funds.com/users/Admin@maple.funds.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    # command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ./cli_maple:/opt/gopath/src/github.com/hyperledger/fabric/peer
    depends_on:
      - fundorderer.funds.com
      - peer0.maple.funds.com
      - peer1.maple.funds.com
      - peer0.fundinc.funds.com
      - peer1.fundinc.funds.com
    networks:
      - byfn
      
  cli_fundinc:
    container_name: cli_fundinc
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli_fundinc
      - CORE_PEER_ADDRESS=peer0.fundinc.funds.com:7051
      - CORE_PEER_LOCALMSPID=fundinc
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/fundinc.funds.com/peers/peer0.fundinc.funds.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/fundinc.funds.com/peers/peer0.fundinc.funds.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/fundinc.funds.com/peers/peer0.fundinc.funds.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/fundinc.funds.com/users/Admin@fundinc.funds.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    # command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ./cli_fundinc:/opt/gopath/src/github.com/hyperledger/fabric/peer
    depends_on:
      - fundorderer.funds.com
      - peer0.maple.funds.com
      - peer1.maple.funds.com
      - peer0.fundinc.funds.com
      - peer1.fundinc.funds.com
    networks:
      - byfn

